//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceDailyTransaction
    {
        public int ID { get; set; }
        public double Amount { get; set; }
        public int DailyTransactionType_P_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual DailyTransactionType_p DailyTransactionType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
